spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0&connectTimeout=30&socketTimeout=60
spring.datasource.username=postgres.otgnhaevwkzxmvjekbmn
spring.datasource.password=Naresh@7143.
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=agridirect_jwt_secret_key_must_be_32_chars_long_minimum
jwt.expiration=86400000

razorpay.key-id=rzp_test_SwdZmhaJQfFvHZ
razorpay.key-secret=oqleXW43h6UZNe0Alcq0patT
razorpay.webhook-secret=agridirect_rzp_webhook_2024

cloudinary.cloud-name=djsq4ltia
cloudinary.api-key=554843327193385
cloudinary.api-secret=IoubM91t8j7CqgudeiU2B0n_lZA

gemini.api-key=YOUR_GEMINI_API_KEY

server.port=8090

